32 page update time is just this with some extra stuff
FRC5892/HeroHours pull request #37
Opened 2024-10-21 17:30 UTC by yyy2356

might have committed some stuff without doing a checkout first. my bad. Just going to merge these two, i havent found any issues with this, so it should probably be good to merge

2024-10-21 18:02 UTC, MichaelStatt-S requested changes

2024-10-21 18:02 UTC, MichaelStatt-S commented on HeroHours/views.py
> +        #print(round((right_now - user.Last_In).total_seconds()))
maybe I'm too persnickety, but can you remove these extra commented out prints?

2024-10-21 18:02 UTC, MichaelStatt-S commented on HeroHours/views.py
> +        change = round((right_now - user.Last_In).total_seconds())
Am I missing something? Can't you just use the existing totalsecound logic?

2024-10-21 18:10 UTC, MichaelStatt-S commented
Why are you merging into 21-make-logout-command-in-page? why not into main

2024-10-21 18:49 UTC, yyy2356 commented on HeroHours/views.py
> +def get_time(orig: float, change: int) -> str:
> Why isn't this just using the function that's already in the model?
when making changes to data, the change is stored as a code block in memory, essentially. to use the built in method on the changed data would require a significant change to the built in method or to save and then re access the data for the user. The first is a problem for obvious reasons, the second is really inefficient, so i opted to do this.

2024-10-21 18:52 UTC, yyy2356 commented
made a mistake and didnt checkout, so the changes are the same on both, except for the most recent 2 commits, where i fix a issue with the login redirect url, not sure when that got in there.

2024-10-22 01:03 UTC, yyy2356 commented
![image](https://github.com/user-attachments/assets/a5e2e67c-d03f-4c58-b0bb-7490a5eeac5b)

2024-10-22 14:25 UTC, MichaelStatt-S approved these changes
Looks good to me!

2024-10-22 15:28 UTC, merged